name: spydir
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
