// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXlnJYd6xsmjLJ0rPWB_gdNOwrJ_2eto0',
    appId: '1:221854001552:web:32ad0f7c0c1743b0086b15',
    messagingSenderId: '221854001552',
    projectId: 'spydir-3d4d5',
    authDomain: 'spydir-3d4d5.firebaseapp.com',
    storageBucket: 'spydir-3d4d5.appspot.com',
    measurementId: 'G-CPVMGF1Z86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjUHki1QmCHJMp31KSDSPsPaYMqrryrE8',
    appId: '1:221854001552:android:4cc7cd63b8c6b52c086b15',
    messagingSenderId: '221854001552',
    projectId: 'spydir-3d4d5',
    storageBucket: 'spydir-3d4d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYppKhbLmbOJD9doVhPqO8iqmqUm3_I7c',
    appId: '1:221854001552:ios:4ddd63bd8c395351086b15',
    messagingSenderId: '221854001552',
    projectId: 'spydir-3d4d5',
    storageBucket: 'spydir-3d4d5.appspot.com',
    iosClientId: '221854001552-brupv6u7mn7pvvulq4b49ueikc8mdtvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.spydir',
  );
}
