// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQKc9q6jtUDWuosqK_G1ckY93FaGeL7Nk',
    appId: '1:909110822733:web:6af11d822c7e14a1f81904',
    messagingSenderId: '909110822733',
    projectId: 'spydir2',
    authDomain: 'spydir2.firebaseapp.com',
    storageBucket: 'spydir2.appspot.com',
    measurementId: 'G-ZN87SXWKGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADs3R40WOc7SYWczsPSbFJ44n-FmcO7rA',
    appId: '1:909110822733:android:a2d037a6b77aae74f81904',
    messagingSenderId: '909110822733',
    projectId: 'spydir2',
    storageBucket: 'spydir2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5eS4q4edSs0VeqfEiDIqKVie9kXclXxE',
    appId: '1:909110822733:ios:9cceb1d5cd4d7d7ef81904',
    messagingSenderId: '909110822733',
    projectId: 'spydir2',
    storageBucket: 'spydir2.appspot.com',
    iosClientId:
        '909110822733-680525qg85dj0l13qnmj10v4ll3350fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5eS4q4edSs0VeqfEiDIqKVie9kXclXxE',
    appId: '1:909110822733:ios:9cceb1d5cd4d7d7ef81904',
    messagingSenderId: '909110822733',
    projectId: 'spydir2',
    storageBucket: 'spydir2.appspot.com',
    iosClientId:
        '909110822733-680525qg85dj0l13qnmj10v4ll3350fm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
